import { ProductGroup } from '../common/interfaces';

const PRICES = {
  'gpt-4o': { input: 0.000005, output: 0.00002 },
  'gpt-4.1-mini': { input: 0.00015, output: 0.0006 },
};

/**
 * Get the predefined product type list
 */
export function getProductTypeList(): string[] {
  return [
    'Hardware',
    'Porcelain/Ceramic Tiling',
    'Mosaic Tiling',
    'Bamboo',
    'Carpet Broadloom',
    'Cork Flooring',
    'Wood Athletic Flooring',
    'Leather Flooring',
    'Linoleum Sheet Flooring',
    'Rubber Sheet Flooring',
    'Terrazzo Floor Tile',
    'Vinyl Composition Tile (VCT) Flooring',
    'Resilient Wall Base',
    'Surfacing Films',
    'Vegetated Wall Systems',
    'Wall Covering',
    'Fabric-Wrapped Panels',
    'Vinyl Sheet Flooring',
    'Brick Masonry',
    'Stone Tiling',
    'Terracotta Tiling',
    'Glass Mosaic Tiling',
    'Metal Tiling',
    'Stretched-Fabric Wall Systems',
    'Stone Wall Facing',
    'Textile Wall Coverings',
    'Wall Carpeting',
    'Stone Trim',
    'Plastic Blocks',
    'Stone-Faced Interior Wall Paneling',
    'Printed Graphics',
    'Phenolic Interior Wall Paneling',
    'Plastic Interior Wall Paneling',
    'Vinyl-Coated Fabric Wall Coverings',
    'Terrazzo Wall Finish',
    'Wood Wall Coverings',
    'Simulated Stone Wall Facing',
    'Metal Interior Wall Paneling',
    'Plaster and Gypsum Board Assemblies',
    'Supports for Plaster and Gypsum Board',
    'Plaster Fabrications',
    'Gypsum Board',
    'Staining and Transparent Finishing',
    'High Performance Coatings',
    'Concrete Forming and Accessories',
    'Cast-in-Place Concrete',
    'Precast Concrete',
    'Cast Decks and Underlayment',
    'Unit Masonry',
    'Clay Unit Masonry',
    'Concrete Unit Masonry',
    'Concrete Unit Veneer Masonry',
    'Surface-Bonded Concrete Unit Masonry',
    'Glass Unit Masonry',
    'Adobe Unit Masonry',
    'Unit Masonry Panels',
    'Single-Wythe Unit Masonry',
    'Multiple-Wythe Unit Masonry',
    'Concrete Form Masonry Units',
    'Engineered Unit Masonry',
    'Stone Assemblies',
    'Dry-Placed Stone',
    'Exterior Stone Cladding',
    'Stone Masonry',
    'Refractory Masonry',
    'Flue Liner Masonry',
    'Combustion Chamber Masonry',
    'Castable Refractory Masonry',
    'Refractory Brick Masonry',
    'Masonry Fireplaces',
    'Corrosion-Resistant Masonry',
    'Chemical-Resistant Brick Masonry',
    'Vitrified Clay Liner Plate',
    'Manufactured Masonry',
    'Manufactured Brick Masonry',
    'Cast Stone Masonry',
    'Manufactured Stone Masonry',
    'Cold-Formed Metal Framing',
    'Metal Fabrications',
    'Decorative Metal',
    'Wood Decking',
    'Thermal Protection',
    'Thermal Insulation',
    'Mirrors',
    'Special Function Glazing',
    'Composition Stone Flooring',
    'Visual Display Units',
    'Wall and Door Protection',
    'Corner Guards',
    'Protective Wall Covering',
    'Toilet, Bath, and Laundry Accessories',
    'Countertops',
    'Window Treatments',
    'Window Blinds',
    'Roller Window Shades',
    'Window Treatment Operating Hardware',
    'Rugs and Mats',
    'Entrance Floor Mats',
    'Furnishings',
    'Special Construction',
    'Swimming Pool Sundries',
    'Sound, Vibration, and Seismic Control',
    'Radiation Protection',
    'Plumbing Piping',
    'Plumbing Fixtures',
    'Concrete Accessories',
    'Fabric and Grid Reinforcing',
    'Paving Specialties',
    'Athletic and Recreational Surfacing',
    'Turf and Grasses',
    'Sundries',
    'Sundries',
    'Suspension System',
    'Acoustical Ceilings',
    'Fire and Smoke Protection',
    'Terrazzo Flooring',
    'Acoustic Underlayment',
    'Concrete Tiling',
    'Joint Protection',
    'Brick Tiling',
    'Accessories',
    'Synthetic Turf Flooring',
    'Static-Dissipative Resilient Flooring',
    'Resilient Stair Treads and Risers',
    'Paver Tiling',
    'Plastic Tiling',
    'Accessories',
    'Sundries',
    'Flexible Wood Veneers',
    'Rigid-Sheet Vinyl Wall Coverings',
    'Concrete Finishing',
    'Quarry Tiling',
    'Resilient Stair Nosings',
    'Conductive Resilient Flooring',
    'Resilient Athletic Flooring',
    'Carpet Tile',
    'Entrance Floor Mats and Frames',
    'Entrance Floor Mat Frames',
    'Entrance Floor Grilles',
    'Entrance Floor Gratings',
    'Entrance Floor Grids',
    'Entrance Tile',
    'Floor Mats',
    'Asphaltic Plank Flooring',
    'Laminate Flooring',
    'Acid-Resistant Flooring',
    'Acoustic Flooring',
    'Aluminum Flooring',
    'Stainless Steel Flooring',
    'Brick Flooring',
    'Wood Block Flooring',
    'Laminated Wood Flooring',
    'Wood Parquet Flooring',
    'Resilient Wood Flooring Assemblies',
    'Rubber Tile Flooring',
    'PVC-Free Sheet Flooring',
    'Static-Resistant Resilient Flooring',
    'Fluid-Applied Athletic Flooring',
    'Cork Wall Coverings',
    'Roofing and Siding Panels',
    'Plastic Fabrications',
    'Mixed Materials',
    'Linoleum Tile Flooring',
    'Luxury Vinyl Tile (LVT)',
    'Flexible Vinyl Wall Coverings',
    'Cementitious Interior Wall Paneling',
    'Grouting',
    'Maintenance of Concrete',
    'Wall Base - Other',
    'Trim',
    'Access Flooring',
    'Architectural Wood Casework',
    'Accessories',
    'Hardware',
    'Schedules for Wood, Plastics, and Composites',
    'Metal Stair Nosings',
    'Expansion Joint Cover Assemblies',
    'Cabinet and Drawer Hardware',
    'Wallpapering',
    'Interior Lighting',
    'Wood Paneling',
    'Composite Fabrications',
    'Membrane Roofing',
    'Steep Slope Roofing',
    'Swimming Pool',
    'Sundries',
    'Wood Stair Nosing',
    'Accessories',
    'Sundries',
    'Accessories',
    'Fixed Sound-Absorptive Panels',
    'Interior Wall Paneling',
    'Countertops',
    'Acoustical Ceiling Suspension Assemblies',
    'Textured Ceilings',
    'Special Function Ceilings',
    'Integrated Ceiling Assemblies',
    'Concrete Plank Flooring',
    'Wood Composition Flooring',
    'Wood Strip and Plank Flooring',
    'Polyester Composition Tile Flooring',
    'Elastomeric Liquid Flooring',
    'Epoxy-Marble Chip Flooring',
    'Magnesium-Oxychloride Flooring',
    'Resinous Flooring',
    'Epoxy Coatings',
    'Gypsum Board Shaft Wall Assemblies',
    'Gypsum Board Area Separation Wall Assemblies',
    'Staining and Transparent Finishing',
    'Pleated Window Shades',
    'Radiant-Heating Electric Cables',
    'Structural Glass Flooring',
    'Stone Flooring',
    'Quartz Flooring',
    'Glass Tiling',
    'Resilient Sheet Flooring',
    'Resilient Tile Flooring',
    'PVC-Free Tile Flooring',
    'Sound-Absorbing Wall Units',
    'Fiber-Cement Siding',
    'Access Flooring Accessories',
    'Access Flooring Stairs and Stringers',
    'Concrete Floor Staining',
    'Low-Profile Fixed Height Access Flooring',
    'Rigid-Grid Access Flooring',
    'Slip-Resistant Flooring Treatment',
    'Snap-on Stringer Access Flooring',
    'Solid Wood Strip and Plank Flooring',
    'Stringerless Access Flooring',
    'Thin-Set Tiling',
    'Thin-Set Ceramic Tiling',
    'Thin-Set Quarry Tiling',
    'Thin-Set Paver Tiling',
    'Thin-Set Glass Mosaic Tiling',
    'Thin-Set Plastic Tiling',
    'Thin-Set Metal Tiling',
    'Thin-Set Stone Tiling',
    'Thin-Set Concrete Tiling',
    'Mortar-Bed Tiling',
    'Mortar-Bed Ceramic Tiling',
    'Mortar-Bed Quarry Tiling',
    'Mortar-Bed Paver Tiling',
    'Mortar-Bed Glass Mosaic Tiling',
    'Mortar-Bed Plastic Tiling',
    'Mortar-Bed Metal Tiling',
    'Mortar-Bed Stone Tiling',
    'Mortar-Bed Concrete Tiling',
    'Conductive Tiling',
    'Conductive Ceramic Tiling',
    'Conductive Quarry Tiling',
    'Conductive Paver Tiling',
    'Conductive Glass Mosaic Tiling',
    'Conductive Plastic Tiling',
    'Conductive Metal Tiling',
    'Conductive Stone Tiling',
    'Conductive Concrete Tiling',
    'Waterproofing-Membrane Tiling',
    'Waterproofing-Membrane Ceramic Tiling',
    'Waterproofing-Membrane Quarry Tiling',
    'Waterproofing-Membrane Paver Tiling',
    'Waterproofing-Membrane Glass Mosaic Tiling',
    'Waterproofing-Membrane Plastic Tiling',
    'Waterproofing-Membrane Metal Tiling',
    'Waterproofing-Membrane Stone Tiling',
    'Waterproofing-Membrane Concrete Tiling',
    'Chemical-Resistant Tiling',
    'Chemical-Resistant Ceramic Tiling',
    'Chemical-Resistant Quarry Tiling',
    'Chemical-Resistant Paver Tiling',
    'Chemical-Resistant Glass Mosaic Tiling',
    'Chemical-Resistant Plastic Tiling',
    'Chemical-Resistant Metal Tiling',
    'Chemical-Resistant Stone Tiling',
    'Chemical-Resistant Concrete Tiling',
    'Flooring Treatment',
    'Static-Resistant Flooring Treatment',
    'Specialty Flooring',
    'Masonry Flooring',
    'Wood Flooring',
    'Resilient Flooring',
    'Resilient Carpet Transitions',
    'Portland Cement Terrazzo Flooring',
    'Sand Cushion Terrazzo Flooring',
    'Monolithic Terrazzo Flooring',
    'Bonded Terrazzo Flooring',
    'Palladina Terrazzo Flooring',
    'Rustic Terrazzo Flooring',
    'Structural Terrazzo Flooring',
    'Portland Cement Terrazzo Floor Tile',
    'Plastic-Matrix Terrazzo Floor Tile',
    'Resinous Matrix Terrazzo Flooring',
    'Epoxy-Resin Terrazzo Flooring',
    'Polyester-Resin Terrazzo Flooring',
    'Conductive Terrazzo Flooring',
    'Conductive Epoxy-Resin Terrazzo',
    'Conductive Polyester-Resin Terrazzo Flooring',
    'Conductive Plastic-Matrix Terrazzo Flooring',
    'Fluid-Applied Flooring',
    'Sundries',
    'Concrete Slip Forming',
    'Concrete Shoring',
    'Falsework',
    'Architectural Cast-in-Place Concrete Forming',
    'Insulating Concrete Forming',
    'Permanent Stair Forming',
    'Permanent Tier Forming',
    'Non-Expanding Waterstops',
    'Expanding Waterstops',
    'Injection Hose Waterstops',
    'Concrete Construction Joints',
    'Cast-In Concrete Anchors',
    'Termite Barrier',
    'Heavyweight Structural Concrete',
    'Lightweight Structural Concrete',
    'Shrinkage-Compensating Structural Concrete',
    'High-Performance Structural Concrete',
    'Ultra High-Performance Structural Concrete',
    'Self-Compacting Concrete',
    'Heavyweight Architectural Concrete',
    'Lightweight Architectural Concrete',
    'Low Density Concrete',
    'High-Tolerance Concrete Floor Finishing',
    'Heavy-Duty Concrete Floor Finishing',
    'Colored Concrete Finishing',
    'Exposed Aggregate Concrete Finishing',
    'Grooved Concrete Surface Finishing',
    'Tooled Concrete Finishing',
    'Stamped Concrete Finishing',
    'Polished and Dyed Concrete Finishing',
    'Polished and Stained Concrete Finishing',
    'Concrete Topical Treatments',
    'Shotcrete',
    'Pumped Concrete',
    'Pneumatically Placed Concrete',
    'Roller-Compacted Concrete',
    'Underwater Placed Concrete',
    'Post-Tensioned Concrete Preparation',
    'Unbonded Post-Tensioned Concrete',
    'Bonded Post-Tensioned Concrete',
    'Water Concrete Curing',
    'Sand Concrete Curing',
    'Chemical Compound Membrane Concrete Curing',
    'Sheet Membrane Concrete Curing',
    'Cementitious Wood Fiber Decks',
    'Gypsum Concrete Roof Decks',
    'Composite Concrete Roof Insulation',
    'Lightweight Cellular Insulating Concrete',
    'Lightweight Aggregate Insulating Concrete',
    'Emery-Aggregate Concrete Topping',
    'Iron-Aggregate Concrete Topping',
    'Concrete Overlayment',
    'Gypsum Cement Underlayment',
    'Hydraulic Cement Underlayment',
    'Cementitious Grouting',
    'Dry-Pack Grouting',
    'Non-Shrink Grouting',
    'Non-Metallic Non-Shrink Grouting',
    'Metallic Non-Shrink Grouting',
    'Epoxy Grouting',
    'Epoxy Injection Grouting',
    'Polyacrylate Modified Cementitious Terrazzo Flooring',
    'Concrete Forming',
    'Combination Expanding and Injection Hose Waterstops',
    'Structural Concrete',
    'Architectural Concrete',
    'Specialty Placed Concrete',
    'Post-Tensioned Concrete',
    'Concrete Curing',
    'Cast Roof Decks',
    'Lightweight Concrete Roof Insulation',
    'Concrete Topping',
    'Cast Underlayment',
    'Injection Grouting',
    'Chair Mats',
    'Anti-Fatigue Floor Mats',
    'Fall-Cushioning Floor Mats',
    'Rugs',
    'Runners',
    'Oriental Rugs',
    'Wood, Plastic, Composite Fastenings',
    'Acoustical Panel Ceilings',
    'Acoustical Fabric-Faced Panel Ceilings',
    'Acoustical Tile Ceilings',
    'Acoustical Wood Ceilings',
    'Acoustical Metal Pan Ceilings',
    'Direct-Applied Acoustical Ceilings',
    'Curved Profile Ceiling Suspension Assemblies',
    'Metal Acoustical Ceiling Suspension Assemblies',
    'Plastic Acoustical Ceiling Suspension Assemblies',
    'Open Metal Mesh Ceilings',
    'Luminous Ceilings',
    'Mirror Panel Ceilings',
    'Metal Pan Ceilings',
    'Linear Metal Ceilings',
    'Suspended Wood Ceilings',
    'Suspended Plastic Ceilings',
    'Decorative Panel Ceilings',
    'Suspended Decorative Grids',
    'Stretched-Fabric Ceiling Systems',
    'Fabric-Wrapped Ceiling Panels',
    'Fiberglass Reinforced Panel Ceilings (FRP)',
    'Gypsum-Panel Textured Ceilings',
    'Metal-Panel Textured Ceilings',
    'Plastic-Panel Textured Ceilings',
    'Security Ceiling Assemblies',
    'Metal Suspension Systems',
    'Plastic Suspension Systems',
    'Stone Base',
    'Stone Window Stools',
    'Special Wall Surfacing',
    'Interior Painting',
    'Acoustic Room Components',
    'Brick Veneer Masonry',
    'Surface-Bonded Brick Masonry',
    'Ceramic Glazed Clay Masonry',
    'Clay Tile Masonry',
    'Structural Clay Tile Masonry',
    'Glazed Structural Clay Tile Masonry',
    'Terra Cotta Masonry',
    'Insulated Concrete Unit Masonry',
    'Architectural Concrete Unit Masonry',
    'Exposed Aggregate Concrete Unit Masonry',
    'Fluted Concrete Unit Masonry',
    'Molded-Face Concrete Unit Masonry',
    'Prefaced Concrete Unit Masonry',
    'Sound-Absorbing Concrete Unit Masonry',
    'Split-Face Concrete Unit Masonry',
    'Autoclaved Aerated Concrete Unit Masonry',
    'Interlocking Concrete Unit Masonry',
    'Vertical Glass Unit Masonry',
    'Glass Unit Masonry Floors',
    'Glass Unit Masonry Skylights',
    'Site-Cast Adobe Unit Masonry',
    'Manufactured Adobe Unit Masonry',
    'Metal-Supported Unit Masonry Panels',
    'Masonry Veneer',
    'Composite Unit Masonry',
    'Cavity Wall Unit Masonry',
    'Dry-Stacked, Concrete-Filled Masonry Units',
    'Mortar-Set, Concrete-Filled Masonry Units',
    'Masonry-Supported Stone Cladding',
    'Steel-Stud-Supported Stone Cladding',
    'Strongback-Frame-Supported Stone Cladding',
    'Truss-Supported Stone Cladding',
    'Grid-System-Supported Stone Cladding',
    'Stone Panels for Curtain Walls',
    'Stone Masonry Veneer',
    'Anchored Stone Masonry Veneer',
    'Adhered Stone Masonry Veneer',
    'Stone Fabrications',
  ];
}

/**
 * Validate and clean the extracted data
 */
export function validateAndCleanData(data: any): ProductGroup[] | 'not_found' {
  if (!Array.isArray(data) || data.length === 0) {
    return 'not_found';
  }

  try {
    const validData: ProductGroup[] = data.map((group) => ({
      designationGroup: group.designationGroup || '',
      products: (group.products || []).map((product: any) => ({
        designation: product.designation || '',
        manufacturerName: product.manufacturerName || '',
        productTypeName: product.productTypeName || '',
        collection: product.collection || '',
        productName: product.productName || '',
        productNumber: product.productNumber || '',
        colorName: product.colorName || '',
        colorNumber: product.colorNumber || '',
        backing: product.backing || '',
        size: product.size || '',
        shape: product.shape || '',
        finish: product.finish || '',
      })),
    }));

    return validData.filter((group) => group.products.length > 0);
  } catch (error) {
    console.error('Data validation failed:', error);
    return 'not_found';
  }
}

export function normalizeAIResult(content: string) {
  try {
    const raw = content;

    const cleaned = raw
      .replace(/^```json\s*/i, '')
      .replace(/\s*```$/, '')
      .trim();

    let parsedResult;
    try {
      parsedResult = JSON.parse(cleaned);
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
    } catch (e) {
      parsedResult = 'not_found';
    }

    return parsedResult;
  } catch (error) {
    console.error('Failed normalize AI response:', error);
    throw new Error('Failed normalize AI response');
  }
}

export const calcCost = (model, inputTokens, outputTokens) => {
  const price = PRICES[model];
  if (!price) throw new Error(`Нет тарифов для модели ${model}`);

  const inputCost = inputTokens * price.input;
  const outputCost = outputTokens * price.output;
  return inputCost + outputCost;
};
